version: 2.1

workflows:
  test-and-build:
    jobs:
    - test
    - build

jobs:
  test:
    docker:
    - image: rust:1.59.0
    working_directory: /app
    steps:
    - run:
        name: Install dependencies
        command: |
          rustup component add rustfmt clippy
    - checkout
    - restore_cache:
        keys:
          - test-v1-{{ checksum "Cargo.lock" }}-
          - test-v1-
    - run:
        name: Check formatting
        command: |
          cargo fmt -- --check --verbose
    - run:
        name: Clippy
        command: |
          cargo clippy --all-targets
    - run:
        name: Test
        command: |
          cargo test
    - save_cache:
        paths:
        - target
        - /usr/local/cargo/registry
        key: test-v1-{{ checksum "Cargo.lock" }}-{{ epoch }}

  build:
    docker:
    - image: clux/muslrust:1.50.0-stable
    working_directory: /app
    steps:
    - checkout
    - restore_cache:
        keys:
        - build-v1-{{ checksum "Cargo.lock" }}-
        - build-v1-
    - run:
        name: Build
        command: |
          cargo build --release
    - save_cache:
        paths:
        - target
        - ~/.cargo/registry
        key: build-v1-{{ checksum "Cargo.lock" }}-{{ epoch }}
    - store_artifacts:
        path: target/x86_64-unknown-linux-musl/release/rust-web-boilerplate
